# Site settings
title: 321 Shear Love
email: stroyan07@gmail.com
description: Stephanie Troyan's 321 Shear Love
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://321shearlove.com/ # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://www.facebook.com/troyan1
github_url:
instagram_url: https://www.instagram.com/321shearlove/
pinterest_url:
slack_url:

# Build settings
markdown: kramdown

